create database	QUANLYSINHVIEN
GO 
USE QUANLYSINHVIEN
CREATE TABLE SINHVIEN
(  MSSV CHAR(5) NOT NULL,
   HOTEN NVARCHAR(20),
   GIOITINH NVARCHAR(5)

)
GO
ALTER TABLE SINHVIEN
ADD CONSTRAINT PR_SINHVIEN
PRIMARY KEY (MSSV)
GO 
CREATE TABLE MONHOC(
  MAMH CHAR(5),
  TENMH NVARCHAR(20),
  NAMXUATBAN INT,
  PRICE FLOAT
  PRIMARY KEY (MAMH)
)
GO
 CREATE TABLE GIAOVIEN
 (
   MGV CHAR(5),
   HOTEN NVARCHAR(20),
   GIOITINH VARCHAR(7) CHECK (GIOITINH IN ('MALE' ,'FEMALE'))
 )
 ALTER TABLE GIAOVIEN
 ADD CONSTRAINT PK_GIAOVIEN
 
 
 GO 
 ALTER TABLE dbo.GIAOVIEN -- CHÚ Ý PHẢI THÊM DBO MỚI CHẠY ĐC TRONG CÁC BẢNG
 ADD CONSTRAINT CK_GIAOVIEN
 CHECK(GIOITINH IN (N'NAM' , N'NỮ'))
 GO
 ALTER TABLE dbo.GIAOVIEN
 ADD CONSTRAINT CK_GIAOVIEN
 PRIMARY KEY (MGV)

 GO
 ALTER TABLE dbo.GIAOVIEN
 ADD SONAMKINHNGHIEM INT