create database	QUANLYSINHVIEN
GO 
USE QUANLYSINHVIEN
CREATE TABLE SINHVIEN
(  MSSV CHAR(5) NOT NULL,
   HOTEN NVARCHAR(20),
   GIOITINH NVARCHAR(5)

)
GO
ALTER TABLE SINHVIEN
ADD CONSTRAINT PR_SINHVIEN
PRIMARY KEY (MSSV)
GO 
CREATE TABLE MONHOC(
  MAMH CHAR(5),
  TENMH NVARCHAR(20),
  NAMXUATBAN INT,
  PRICE FLOAT
  PRIMARY KEY (MAMH)
)
GO
 CREATE TABLE GIAOVIEN
 (
   MGV CHAR(5),
   HOTEN NVARCHAR(20),
   GIOITINH VARCHAR(7) CHECK (GIOITINH IN ('MALE' ,'FEMALE'))
 )
 ALTER TABLE GIAOVIEN
 ADD CONSTRAINT PK_GIAOVIEN
 
 
 GO 
 ALTER TABLE dbo.GIAOVIEN -- CHÚ Ý PHẢI THÊM DBO MỚI CHẠY ĐC TRONG CÁC BẢNG
 ADD CONSTRAINT CK_GIAOVIEN
 CHECK(GIOITINH IN (N'NAM' , N'NỮ'))
 GO
 ALTER TABLE dbo.GIAOVIEN
 ADD CONSTRAINT CK_GIAOVIEN
 PRIMARY KEY (MGV)

 GO
 ALTER TABLE dbo.GIAOVIEN
 ADD SONAMKINHNGHIEM INT
  
GO 
ALTER TABLE dbo.GIAOVIEN
ADD MAKHOA CHAR(5)
GO 
CREATE TABLE KHOA
(   MAKHOA CHAR(5),
    TENKHOA NVARCHAR(20)
	PRIMARY KEY (MAKHOA)
)
GO 
ALTER TABLE dbo.GIAOVIEN
ADD CONSTRAINT FK_GV_KHOA

FOREIGN KEY (MAKHOA)
REFERENCES dbo.KHOA (MAKHOA)

go 
ALTER TABLE GIAOVIEN
ADD CONSTRAINT PK_GIAOVIEN
PRIMARY KEY (MGV)
go 
ALTER TABLE GIAOVIEN
ADD NGAYSINH DATE 
 
 ALTER TABLE KHOA
 ADD NGAYTHANHLAP DATE
 

 INSERT INTO KHOA(MAKHOA,TENKHOA,NGAYTHANHLAP) VALUES('KH001','CONG THONG TT','11/25/1994')

 INSERT INTO KHOA(MAKHOA,TENKHOA,NGAYTHANHLAP) VALUES('KH002',N'HỆ THỐNG','1994/11/25')
 INSERT INTO GIAOVIEN(MGV,HOTEN,GIOITINH,SONAMKINHNGHIEM,MAKHOA,NGAYSINH)
 VALUES (001,N'NGUYỄN VĂN THIỆN',N'NAM',4.5,NULL,'11/02/1995')
  INSERT INTO GIAOVIEN(MGV,HOTEN,GIOITINH,SONAMKINHNGHIEM,MAKHOA,NGAYSINH)
 VALUES (001,N'NGUYỄN THỊ YẾN',N'NỮ',5.2,NULL,'09/26/1995')